### ISSUE TITLE
MP3 and WAV are "unsupported file types"? Something's wrong...

### ISSUE THREAD

**Issue by bithub2** [arkrow/PyMusicLooper#1]
So I tried using the PyMusicLooper and it skipped my MP3 and WAV files because they were "unsupported". The problem is: you say that MP3 and WAV are both supported. How do I fix this error?

**Comment by bithub2** [comment]
Do you even know that I made this issue? It's been 20 minutes and I still haven't gotten a response. I haven't been able to fix it at all, so PLEASE HELP ME!!!

**Comment by arkrow** [comment]
You likely haven't installed [ffmpeg](https://ffmpeg.org), which this package requires to decode different audio files. Assuming that you are on Windows, you can follow the following [WikiHow guide](https://www.wikihow.com/Install-FFmpeg-on-Windows) to get ffmpeg installed and working. If you can run `ffmpeg -version` in the terminal, PyMusicLooper should be able to load any audio format that is supported by ffmpeg.
