### ISSUE TITLE
Cannot process any file

### ISSUE THREAD

**Issue by cssobral2013** [arkrow/PyMusicLooper#10]
**Describe the bug**
As stated in title, I cannot process any file because of error below.
**Debugging Information**
The error displayed is just:
LLVM ERROR: Symbol not found: __svml_cosf8_ha

**Expected behavior**
It should process any files correctly

**Desktop (please complete the following information):**
 - OS: Windows 11
 - FFmpeg is installed and working

**Comment by arkrow** [comment]
This looks like a numba/llvmlite related error, not an error with pymusiclooper itself. That said, a solution can be found on the following thread: https://github.com/lmcinnes/umap/issues/702#issuecomment-1002396093/

**Comment by cssobral2013** [comment]
@arkrow - Could you please reopen this issue? Tried that, but is not working.

**Comment by cssobral2013** [comment]
@arkrow - Nevermind it. I just upgrade numba & llvmlite, and it fixed this issue. Thank you!
