### ISSUE TITLE
Create songs of a specific length?

### ISSUE THREAD

**Issue by mnpenner** [arkrow/PyMusicLooper#14]
**Is your feature request related to a problem? Please describe.**

Looks like this program can create loops, intros and outros and give approximate length for the loop portion, any chance it could generate songs of a specific length with the intro and outro and use the loop to stretch or shrink the song to that length? e.g. I want a song exactly 2 min 37 sec to fit a home video.

**Describe the solution you'd like**

Add `--length` option in seconds

**Describe alternatives you've considered (if relevant)**

n/a

**Additional context**

This looks cool, thanks for sharing this!

**Comment by arkrow** [comment]
This sounds like a really specific use case that'd be hard to generalize, and as such it's probably better to manually edit the audio (using the split files from PyMusicLooper) as desired using a program like Audacity.

I could, however, add a new command to **extend** the track to *at least* (not exactly) a desired length, by repeating the loop section between the intro and outro as many times as needed. The output would be similar to those extended edits of music on YouTube. Not sure if it overlaps with your original enhancement idea; an "exact" length requires manual editing but an "at least" constraint is feasible to implement in this case.

**Comment by mnpenner** [comment]
An "at least" would probably help, then I could fade the start/end out if needed. Others might want it if they want to extend a song out to an hour or something.
