### ISSUE TITLE
Won't process the Audio file correctly

### ISSUE THREAD

**Issue by BDAFINNEST** [arkrow/PyMusicLooper#34]
*Before continuing with the bug report, does updating to the latest version fix this issue?* no

**Describe the bug**
Everytime Pymusiclooper starts to process the audio or URL I have chosen it'll just say "ERROR    unsupported format string passed to numpy.ndarray.__format__" a bit after when it says it's processing.

**Debugging Information**
pymusiclooper -i play --url "https://www.youtube.com/watch?v=dQw4w9WgXcQ"

**Expected behavior**
Play the song on repeat with the best discovered loop point.

**Environment Information (please complete the following information):**
- OS: windows 11
- PyMusicLooper version being used (execute `pymusiclooper --version` in the terminal if unsure): pymusiclooper 3.4.0
- Is FFmpeg installed and working? (execute `ffmpeg --version` in the terminal if unsure): yes

**Additional context**
I tried reinstalling pymusiclooper and reinstalling ffmpeg put nothing seems to work

**Comment by arkrow** [comment]
Thanks for reporting @BDAFINNEST. It seems librosa was recently updated and changed how bpm is returned. I've updated PyMusicLooper accordingly and it should be fixed now in v3.4.1.

Let me know if that resolved the issue for you as well after updating.

**Comment by BDAFINNEST** [comment]
It's working now, Thank you!
