### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by LastMonopoly** [arkrow/PyMusicLooper#6]
**Describe the bug**
Not working when my music is 10 seconds long

**Debugging Information**
/usr/local/lib/python3.9/site-packages/librosa/util/decorators.py:88: UserWarning: PySoundFile failed. Trying audioread instead.
  return f(*args, **kwargs)
INFO: Loaded '常青_7142339610037717768.mp3'. Analyzing...
/usr/local/lib/python3.9/site-packages/librosa/core/convert.py:1332: RuntimeWarning: divide by zero encountered in log10
  + 2 * np.log10(f_sq)
INFO: Detected 61 beats at 123 bpm
INFO: Finished initial audio processing in 0.267s
INFO: Found 0 possible loop points
Traceback (most recent call last):
  File "/usr/local/bin/pymusiclooper", line 8, in <module>
    sys.exit(cli_main())
  File "/usr/local/lib/python3.9/site-packages/pymusiclooper/__main__.py", line 243, in cli_main
    loop_start, loop_end, score = choose_loop_pair(loop_pair_list, args.path)
  File "/usr/local/lib/python3.9/site-packages/pymusiclooper/__main__.py", line 111, in choose_loop_pair
    loop_start = loop_pair_list[index]["loop_start"]
IndexError: list index out of range

**Desktop (please complete the following information):**
 - OS: iMac macOS Ventura
 - Is FFmpeg installed and working? (execute `ffmpeg --version` in the terminal if unsure): ffmpeg version 5.1. YES

**Additional context**
Here is the music
[常青_7142339610037717768.mp3.zip](https://github.com/arkrow/PyMusicLooper/files/10172740/_7142339610037717768.mp3.zip)

**Comment by arkrow** [comment]
Fixed in v2.5.3. However, no loop points were detected with the current algorithm for your provided sample. I'll consider adding a fallback for tracks with less distinct "beats" / loop points with the next major version release.
