### ISSUE TITLE
Switch mpg123 to another lib like mpg123

### ISSUE THREAD

**Issue by RERASER** [arkrow/PyMusicLooper#8]
**Is your feature request related to a problem? Please describe.**
It look like preview and play feature doesn't work with Windows,because https://github.com/20tab/mpg123-python works not well on Windows.
**Describe the solution you'd like**
FFPYPLAYER is a pylib player using ffmpeg,and PyMusicLooper must works with ffmpeg.
We can use FFPYPLAYER instead of mpg123 or another lib like mpg123

**Describe alternatives you've considered**
Use FFPlay Directly?

**Comment by arkrow** [comment]
Currently, the multi-platform [python sounddevice](https://github.com/spatialaudio/python-sounddevice/) is being looked into as an alternative. Since this is a major change requiring code refactoring and rewrite, it will be released with the next major version release (v3.0).

**Comment by arkrow** [comment]
Update: fixed in v3.0.0 thanks to a re-implementation of playback using python sounddevice, which has better cross-platform compatibility and does not rely on external libraries like mpg123
